/*
 * GitHub Gists
 * defaultDescription
 *
 * OpenAPI spec version: 3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package eu.hohenegger.gister.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.v3.oas.annotations.media.Schema;
/**
 * GistFile
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-08-16T08:33:00.108Z[GMT]")
public class GistFile {
  @JsonProperty("filename")
  private String filename = null;

  @JsonProperty("type")
  private String type = null;

  @JsonProperty("language")
  private String language = null;

  @JsonProperty("raw_url")
  private String rawUrl = null;

  @JsonProperty("size")
  private Integer size = null;

  @JsonProperty("truncated")
  private Boolean truncated = null;

  @JsonProperty("content")
  private String content = null;

   /**
   * Get filename
   * @return filename
  **/
  @Schema(description = "")
  public String getFilename() {
    return filename;
  }

   /**
   * Get type
   * @return type
  **/
  @Schema(description = "")
  public String getType() {
    return type;
  }

   /**
   * Get language
   * @return language
  **/
  @Schema(description = "")
  public String getLanguage() {
    return language;
  }

   /**
   * Get rawUrl
   * @return rawUrl
  **/
  @Schema(description = "")
  public String getRawUrl() {
    return rawUrl;
  }

   /**
   * Get size
   * @return size
  **/
  @Schema(description = "")
  public Integer getSize() {
    return size;
  }

   /**
   * Get truncated
   * @return truncated
  **/
  @Schema(description = "")
  public Boolean isTruncated() {
    return truncated;
  }

  public GistFile content(String content) {
    this.content = content;
    return this;
  }

   /**
   * Get content
   * @return content
  **/
  @Schema(description = "")
  public String getContent() {
    return content;
  }

  public void setContent(String content) {
    this.content = content;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GistFile gistFile = (GistFile) o;
    return Objects.equals(this.filename, gistFile.filename) &&
        Objects.equals(this.type, gistFile.type) &&
        Objects.equals(this.language, gistFile.language) &&
        Objects.equals(this.rawUrl, gistFile.rawUrl) &&
        Objects.equals(this.size, gistFile.size) &&
        Objects.equals(this.truncated, gistFile.truncated) &&
        Objects.equals(this.content, gistFile.content);
  }

  @Override
  public int hashCode() {
    return Objects.hash(filename, type, language, rawUrl, size, truncated, content);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GistFile {\n");
    
    sb.append("    filename: ").append(toIndentedString(filename)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    language: ").append(toIndentedString(language)).append("\n");
    sb.append("    rawUrl: ").append(toIndentedString(rawUrl)).append("\n");
    sb.append("    size: ").append(toIndentedString(size)).append("\n");
    sb.append("    truncated: ").append(toIndentedString(truncated)).append("\n");
    sb.append("    content: ").append(toIndentedString(content)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
