/*
 * GitHub Gists
 * defaultDescription
 *
 * OpenAPI spec version: 3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package eu.hohenegger.gister.model;

import java.time.OffsetDateTime;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.v3.oas.annotations.media.Schema;
/**
 * HistoryEntry
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-08-16T08:33:00.108Z[GMT]")
public class HistoryEntry {
  @JsonProperty("url")
  private String url = null;

  @JsonProperty("version")
  private String version = null;

  @JsonProperty("user")
  private User user = null;

  @JsonProperty("change_status")
  private ChangeStatus changeStatus = null;

  @JsonProperty("committed_at")
  private OffsetDateTime committedAt = null;

  public HistoryEntry url(String url) {
    this.url = url;
    return this;
  }

   /**
   * Get url
   * @return url
  **/
  @Schema(description = "")
  public String getUrl() {
    return url;
  }

  public void setUrl(String url) {
    this.url = url;
  }

  public HistoryEntry version(String version) {
    this.version = version;
    return this;
  }

   /**
   * Get version
   * @return version
  **/
  @Schema(description = "")
  public String getVersion() {
    return version;
  }

  public void setVersion(String version) {
    this.version = version;
  }

  public HistoryEntry user(User user) {
    this.user = user;
    return this;
  }

   /**
   * Get user
   * @return user
  **/
  @Schema(description = "")
  public User getUser() {
    return user;
  }

  public void setUser(User user) {
    this.user = user;
  }

  public HistoryEntry changeStatus(ChangeStatus changeStatus) {
    this.changeStatus = changeStatus;
    return this;
  }

   /**
   * Get changeStatus
   * @return changeStatus
  **/
  @Schema(description = "")
  public ChangeStatus getChangeStatus() {
    return changeStatus;
  }

  public void setChangeStatus(ChangeStatus changeStatus) {
    this.changeStatus = changeStatus;
  }

  public HistoryEntry committedAt(OffsetDateTime committedAt) {
    this.committedAt = committedAt;
    return this;
  }

   /**
   * Get committedAt
   * @return committedAt
  **/
  @Schema(description = "")
  public OffsetDateTime getCommittedAt() {
    return committedAt;
  }

  public void setCommittedAt(OffsetDateTime committedAt) {
    this.committedAt = committedAt;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HistoryEntry historyEntry = (HistoryEntry) o;
    return Objects.equals(this.url, historyEntry.url) &&
        Objects.equals(this.version, historyEntry.version) &&
        Objects.equals(this.user, historyEntry.user) &&
        Objects.equals(this.changeStatus, historyEntry.changeStatus) &&
        Objects.equals(this.committedAt, historyEntry.committedAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(url, version, user, changeStatus, committedAt);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class HistoryEntry {\n");
    
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    user: ").append(toIndentedString(user)).append("\n");
    sb.append("    changeStatus: ").append(toIndentedString(changeStatus)).append("\n");
    sb.append("    committedAt: ").append(toIndentedString(committedAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
